name: Run Features

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: [self-hosted, macos]

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        gem install bundler
        bundle install
        bundle exec cucumber features
